turbine_table_header_keys = [
    "Turbine.isentropic_velocity_ratio",
    "Turbine.correlated_velocity_ratio",
    "Turbine.pressure_ratio",
    "Turbine.mean_diameter",
    "Turbine.an2_stress",
    "Turbine.efficiency",
    "Turbine.power",
    "Turbine.partial_admission_ratio",
    "Turbine.blade_height"
]
turbine_table_header_units = [
    "-",
    "-",
    "-",
    "mm",
    '-',
    "-",
    "kW",
    "-",
    "mm"
]

general_keys = [
    "mass_flow",
    "station_3.total_pressure",
    "npsh_required",
    "shaft_radius",
    "total_efficiency",
    "shaft_power",
    "station_1i.total_pressure",
    "impeller.hub.outlet.radius",
    "station_2.total_pressure",
    "volute.total_head_loss"
]
general_keys_units = [
    "kg/s",
    "bar",
    "m",
    "mm",
    "-",
    "kW",
    "bar",
    "mm",
    "bar",
    "m"
]

keys = [
    # Pump General
    "mass_flow",
    "pressure_rise",
    "npsh_available",
    "is_second_stage",
    "npsh_required",
    "shaft_radius",
    "total_efficiency",
    "hydraulic_efficiency",
    "shaft_power",

    # Inducer
    "inducer_need",
    "inducer.npsh_required",
    "inducer.inlet.flow_coef",
    "inducer.inlet.sigma_b",
    "inducer.inlet.tip.radius",
    "inducer.inlet.tip.alpha",
    "inducer.inlet.tip.beta",
    "inducer.inlet.tip.c",
    "inducer.inlet.tip.c_m",
    "inducer.inlet.tip.c_u",
    "inducer.inlet.tip.u",
    "inducer.inlet.tip.w",
    "inducer.inlet.hub.radius",
    "inducer.inlet.hub.alpha",
    "inducer.inlet.hub.beta",
    "inducer.inlet.hub.c",
    "inducer.inlet.hub.c_m",
    "inducer.inlet.hub.c_u",
    "inducer.inlet.hub.u",
    "inducer.inlet.hub.w",
    "inducer.outlet.total",
    "inducer.outlet.static",
    "inducer.outlet.tip.radius",
    "inducer.outlet.tip.alpha",
    "inducer.outlet.tip.beta",
    "inducer.outlet.tip.c",
    "inducer.outlet.tip.c_m",
    "inducer.outlet.tip.c_u",
    "inducer.outlet.tip.u",
    "inducer.outlet.tip.w",
    "inducer.outlet.hub.radius",
    "inducer.outlet.hub.alpha",
    "inducer.outlet.hub.beta",
    "inducer.outlet.hub.c",
    "inducer.outlet.hub.c_m",
    "inducer.outlet.hub.c_u",
    "inducer.outlet.hub.u",
    "inducer.outlet.hub.w",
    "inducer.blade_number",
    "inducer.l_over_t",
    "inducer.head_rise",
    "inducer.head_loss",
    "inducer.hydraulic_efficiency",

    # Impeller
    "impeller.NPSH",
    "impeller.inlet.flow_coef",
    "impeller.blade.inlet.tip.radius",
    "impeller.blade.inlet.tip.alpha",
    "impeller.blade.inlet.tip.beta",
    "impeller.blade.inlet.tip.c",
    "impeller.blade.inlet.tip.c_m",
    "impeller.blade.inlet.tip.c_u",
    "impeller.blade.inlet.tip.u",
    "impeller.blade.inlet.tip.w",
    "impeller.blade.inlet.hub.radius",
    "impeller.blade.inlet.hub.alpha",
    "impeller.blade.inlet.hub.beta",
    "impeller.blade.inlet.hub.c",
    "impeller.blade.inlet.hub.c_m",
    "impeller.blade.inlet.hub.c_u",
    "impeller.blade.inlet.hub.u",
    "impeller.blade.inlet.hub.w",
    "impeller.outlet.radius",
    "impeller.outlet.width",
    "impeller.outlet.alpha",
    "impeller.blade.outlet.beta",
    "impeller.outlet.c",
    "impeller.outlet.c_m",
    "impeller.outlet.c_u",
    "impeller.outlet.u",
    "impeller.outlet.w",
    "impeller.outlet.gama",
    "impeller.outlet.total",
    "impeller.outlet.static",
    "impeller.blade_number",
    "impeller.head_rise",
    "impeller.head_loss",
    "impeller.hydraulic_efficiency",
    "impeller.specific_speed",
    "impeller.specific_speed_ft",
    "impeller.specific_diameter_ft",

    # Impeller 2
    "impeller2.NPSH",
    "impeller2.inlet.flow_coef",
    "impeller2.blade.inlet.tip.radius",
    "impeller2.blade.inlet.tip.alpha",
    "impeller2.blade.inlet.tip.beta",
    "impeller2.blade.inlet.tip.c",
    "impeller2.blade.inlet.tip.c_m",
    "impeller2.blade.inlet.tip.c_u",
    "impeller2.blade.inlet.tip.u",
    "impeller2.blade.inlet.tip.w",
    "impeller2.blade.inlet.hub.radius",
    "impeller2.blade.inlet.hub.alpha",
    "impeller2.blade.inlet.hub.beta",
    "impeller2.blade.inlet.hub.c",
    "impeller2.blade.inlet.hub.c_m",
    "impeller2.blade.inlet.hub.c_u",
    "impeller2.blade.inlet.hub.u",
    "impeller2.blade.inlet.hub.w",
    "impeller2.outlet.radius",
    "impeller2.outlet.height",
    "impeller2.outlet.alpha",
    "impeller2.blade.outlet.beta",
    "impeller2.outlet.c",
    "impeller2.outlet.c_m",
    "impeller2.outlet.c_u",
    "impeller2.outlet.u",
    "impeller2.outlet.w",
    "impeller2.outlet.gama",
    "impeller2.outlet.total",
    "impeller2.outlet.static",
    "impeller2.blade_number",
    "impeller2.head_rise",
    "impeller2.head_loss",
    "impeller2.hydraulic_efficiency",
    "impeller2.specific_speed",
    "impeller2.specific_speed_ft",
    "impeller2.specific_diameter_ft",

    # Volute
    "volute.total_arc_length",
    "volute.total_wet_surface_area",
    "volute.friction_loss",
    "volute.meridional_dump_loss",
    "volute.tangential_dump_loss",
    "volute.total_loss",

    # Diffuser
    "diffuser.AR_opt",
    "diffuser.head_loss_total",
    "diffuser.lenght",
    "diffuser.pressure_recovery_opt",
    "diffuser.static_pressure_rise",
    "diffuser.total_pressure_loss",
    "diffuser.inlet_3.alpha",
    "diffuser.inlet_3.area",
    "diffuser.inlet_3.height",
    "diffuser.inlet_3.radius",
    "diffuser.inlet_3.radius_throat",
    "diffuser.inlet_3.total",
    "diffuser.inlet_3.width",
    "diffuser.outlet_4.alpha",
    "diffuser.outlet_4.area",
    "diffuser.outlet_4.height",
    "diffuser.outlet_4.radius",
    "diffuser.outlet_4.radius_throat",
    "diffuser.outlet_4.total",
    "diffuser.outlet_4.width",
    "diffuser.inlet_5.alpha",
    "diffuser.inlet_5.area",
    "diffuser.inlet_5.height",
    "diffuser.inlet_5.radius",
    "diffuser.inlet_5.radius_throat",
    "diffuser.inlet_5.total",
    "diffuser.inlet_5.width",
    "diffuser.outlet_6.alpha",
    "diffuser.outlet_6.area",
    "diffuser.outlet_6.height",
    "diffuser.outlet_6.radius",
    "diffuser.outlet_6.radius_throat",
    "diffuser.outlet_6.total",
    "diffuser.outlet_6.width"




    # "impeller.outlet.radius",
    # "impeller.specific_speed_ft",
    # "impeller.specific_diameter_ft",
    # "impeller2.specific_speed_ft",
    # "impeller2.specific_diameter_ft",
    # "impeller.hydraulic_efficiency",
    # "impeller2.hydraulic_efficiency"

]
